
-- RANKING DE LAS FECHAS DEL DOLAR-EURO
	DROP TABLE RANK_EURUSD5;
	select a.*
		,RANK() OVER (ORDER BY a.FECHA ASC) AS Rank
		
			INTO RANK_EURUSD5
		from TN_EURUSD5 AS a
		
	
-- CALCULO EL RETORNO  DE CADA PERIODO 
	DROP TABLE RETORNO_EURUSD5;
		select a.*
			   ,(b.CIERRE - a.CIERRE) / a.CIERRE as RETORNO
			   ,(b.CIERRE - a.CIERRE)* 10000 as DIF_PUNTOS
			   
			   
			INTO RETORNO_EURUSD5
		from RANK_EURUSD5 AS a
		LEFT JOIN RANK_EURUSD5 AS b
		ON(a.Rank = b.Rank - 1)
		
		
		
-- Analisis del retorno y volatilidad a nivel horario	
	DROP TABLE ANALISIS_HORARIO;
	select 
		DATEPART(HOUR,FECHA) AS HORA	
		,AVG(CIERRE) AS VALOR_MEDIO
		,AVG(RETORNO) AS RETORNO_MEDIO
		,STDEV(RETORNO) AS VOLATILIDAD
			INTO ANALISIS_HORARIO
			FROM RETORNO_EURUSD5
			GROUP BY DATEPART(HOUR,FECHA) 
			
			
			
select 	FECHA,CIERRE
		from TN_EURUSD5
	
		ORDER BY FECHA ASC	
		
		
		
		SELECT * FROM TN_EURUSD1
		where YEAR(FECHA) = 2011
		ORDER BY fECHA
	